from pydantic import BaseModel
from typing import List

"""
This file defines the Pydantic schemas for responses sent by AI Assistant, used by langchain parser.
"""
class SourceQuotation(BaseModel):
    """
    Defines the schema of quoted sorces in the AI response
    """
    source: str
    quoted_context: str

class AssistantResponse(BaseModel):
    """
    This schema defines the structure of response generated by AI Assistant.
    """
    question: str
    answer: str
    sources: List[SourceQuotation]
    confidence: float