from sqlmodel import SQLModel, Field
from datetime import datetime
from typing import Optional, List, Dict
from sqlalchemy import Column, JSON

class MetadataDocument(SQLModel, table=True):
    """
    SQLModel to store metadata about each document uploaded. 
    """
    id: Optional[int] = Field(default=None, primary_key=True) # identifier primary key
    filename: str # name of uploaded file
    upload_time: datetime = Field(default_factory=datetime.utcnow) # time uploaded
    chunk_count: Optional[int] = None # no. of chuks retrieved form the file 
    vector_collection: Optional[str] = None # the vector collections it is embedded in 

class QueryLog(SQLModel, table=True):
    """
    SQLModel to store query logs.
    """
    id: Optional[int] = Field(default=None, primary_key=True) # identifier primary key
    question: Optional[str]=None # question asked to llm
    answer: Optional[str]=None # answer generated by llm
    # IDs of documents referenced as source in generating the answer.
    document_ids: Optional[List[Dict]] = Field(
        default=None,
        sa_column=Column(JSON)
    )
    # the confidence put by LLM in the answer generated by itself. 
    confidence: Optional[str]=None
    timestamp: datetime=Field(default_factory=datetime.utcnow) # Timestamp at which the query and response were logged.
